#
# Copyright (c) Microsoft Corporation
# Licensed under the MIT License.
#

name: caf_landing_zones_github_actions 

on:
  push:
    branches:
      - master
      - vnext
  pull_request:
    branches:
      - master
      - vnext

jobs:
  tfsec:
    name: Run TFsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docs:
    name: Run Terraform-docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Run Terraform-docs
      uses: Dirrk/terraform-docs@v1.0.8
      with:
        tf_docs_working_dir: .
        tf_docs_output_file: README.md
        tf_docs_output_method: inject
        tf_docs_git_push: 'true'